### PR TITLE
Update RegionTeleportCommands.java

### PR DESCRIPTION
**Pull request by n-tdi**
Added final descriptor to function arguments to match SpigotMC practices.

### CODE REVIEW

**Review by DrakePork — CHANGES_REQUESTED** [review]
Ah yeah made this part a few years ago so havn't updated it to this, thanks.

However colourMessage can't be final as the message is edited inside of it.

**Comment by n-tdi** [comment]
Got it!

**Comment by n-tdi** [comment]
Fixed final methods from not actually being final

**Review by DrakePork — APPROVED** [review]
Tested and it works woo

**Pull request merged**
